name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - infra
      - .github/workflows/terraform.yaml
  workflow_dispatch:

jobs:
  terraform:
    defaults:
      run:
        working-directory: ./infra
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    name: terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
          terraform_version: ">= 1.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
