name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - infra
  workflow_dispatch:

jobs:
  terraform:
    defaults:
      run:
        working-directory: ./infra
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    name: terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
          terraform_version: ">= 1.2"

      - name: Terraform Init
        run: terraform init

      - id: plan
        run: terraform plan -no-color
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
