name: Terraform Deployment CI/CD

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**/*.yaml
      - infra/**/*
      - services/lambdas/**/*
  workflow_dispatch:

jobs:
  lambdas:
    defaults:
      run:
        working-directory: ./services/lambdas
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Node Build Lambdas
        run: "npm run build"

  terraform:
    defaults:
      run:
        working-directory: ./infra
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    name: terraform
    needs: [lambdas]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
          terraform_version: ">= 1.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply
